import globals from 'globals'
import js from '@eslint/js'

export default [
    js.configs.recommended,
    {
        ignores: [
            'Background.js',
            'Player.js',
            'Screen.js',
            'Sprite.js',
            'SpriteManager.js',
            'Weapon.js',
            'AudioManager.js',
            'CommentaryAudioCache.js',
            'CommentaryService.js',
            'CommentaryVoiceSample.js',
            'OverlayScreen.js',
            'Game.js',
            'GameScene.js',
            'TextureManager.js',
            'utils.js',
            'index.js',
            'textures.js',
            'raycasting.html',
            'game/',
            'scripts/',
            'vite.config.js',
            'node_modules/',
            'dist/',
            'docs/',
            '.husky/',
            '.vite/',
            'coverage/',
            '*.config.cjs',
        ],
    },
    {
        files: ['src/**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                ...globals.browser,
                ...globals.node,
                speechSynthesis: true,
                SpeechSynthesisUtterance: true,
                AudioContext: true,
                fetch: true,
                AbortController: true,
            },
        },
        rules: {
            'no-unused-vars': ['warn', { vars: 'all', args: 'after-used', ignoreRestSiblings: true, caughtErrors: 'none' }],
            'no-undef': 'warn',
            'prefer-const': 'warn',
            'arrow-parens': ['warn', 'always'],
            'curly': ['warn', 'all'],
            'eqeqeq': ['warn', 'always'],
            'no-console': ['warn', { allow: ['error', 'warn', 'info'] }],
            'semi': ['warn', 'never'],
            'quotes': ['warn', 'single'],
            'no-trailing-spaces': 'warn',
            'eol-last': 'warn',
            'comma-dangle': ['warn', { arrays: 'always-multiline', objects: 'always-multiline', imports: 'always-multiline', exports: 'always-multiline', functions: 'never' }],
        },
    },
]
